name: rustls-libssl

on:
  push:

jobs:
  build-nixos:
    name: Test NixOS+Nginx
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - name: Run NixOS test
        run: nix-build ./tests/nixos.nix
